
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author marcos
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    boolean jogador = true;
    String jogador1 = "X";
    String jogador2 = "O";
    String simbolo = "";

    String[][] tabuleiro;        // <- criamos um tabuleiro em matriz para conseguir verificar vencedor

    public void reiniciar() {
        tabuleiro = new String[4][4]; // <- 4x4 para comecar no 1 :)
        jb11.setEnabled(true);
        jb12.setEnabled(true);
        jb13.setEnabled(true);
        jb21.setEnabled(true);
        jb22.setEnabled(true);
        jb23.setEnabled(true);
        jb31.setEnabled(true);
        jb32.setEnabled(true);
        jb33.setEnabled(true);
        jb11.setText("");
        jb12.setText("");
        jb13.setText("");
        jb21.setText("");
        jb22.setText("");
        jb23.setText("");
        jb31.setText("");
        jb32.setText("");
        jb33.setText("");
        jogador = true;
    }

    public String checarVencedor() {
        for (int i = 1; i <= 3; i++) {
            if (tabuleiro[i][1] != null
                    && tabuleiro[i][1].equals(tabuleiro[i][2])
                    && tabuleiro[i][2].equals(tabuleiro[i][3])) {
                return simbolo;
            }
        }
        for (int j = 1; j <= 3; j++) {
            if (tabuleiro[1][j] != null
                    && tabuleiro[1][j].equals(tabuleiro[2][j])
                    && tabuleiro[2][j].equals(tabuleiro[3][j])) {
                return simbolo;
            }
        }
        if (tabuleiro[1][1] != null
                && tabuleiro[1][1].equals(tabuleiro[2][2])
                && tabuleiro[2][2].equals(tabuleiro[3][3])) {
            return simbolo;
        }
        if (tabuleiro[1][3] != null
                && tabuleiro[1][3].equals(tabuleiro[2][2])
                && tabuleiro[2][2].equals(tabuleiro[3][1])) {
            return simbolo;
        }
        return "";
    }

    public void verificarVencedor() {
        String vencedor = checarVencedor();
        if (!vencedor.equals("")) {
            JOptionPane.showMessageDialog(this, "Jogador " + vencedor + " venceu!");
            reiniciar();
        }
    }

    public String jogada() {
        if (jogador == true) {
            jogador = false;
            return jogador1;
        } else {
            jogador = true;
            return jogador2;
        }

    }

    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb21 = new javax.swing.JButton();
        jb31 = new javax.swing.JButton();
        jb11 = new javax.swing.JButton();
        jb12 = new javax.swing.JButton();
        jb22 = new javax.swing.JButton();
        jb32 = new javax.swing.JButton();
        jb13 = new javax.swing.JButton();
        jb23 = new javax.swing.JButton();
        jb33 = new javax.swing.JButton();
        jbInit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho P2 - POO");

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setToolTipText("");

        jb21.setBackground(new java.awt.Color(0, 0, 0));
        jb21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb21.setEnabled(false);
        jb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb21ActionPerformed(evt);
            }
        });

        jb31.setBackground(new java.awt.Color(0, 0, 0));
        jb31.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb31.setEnabled(false);
        jb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb31ActionPerformed(evt);
            }
        });

        jb11.setBackground(new java.awt.Color(0, 0, 0));
        jb11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb11.setEnabled(false);
        jb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb11ActionPerformed(evt);
            }
        });

        jb12.setBackground(new java.awt.Color(0, 0, 0));
        jb12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb12.setToolTipText("");
        jb12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb12.setEnabled(false);
        jb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb12ActionPerformed(evt);
            }
        });

        jb22.setBackground(new java.awt.Color(0, 0, 0));
        jb22.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb22.setEnabled(false);
        jb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb22ActionPerformed(evt);
            }
        });

        jb32.setBackground(new java.awt.Color(0, 0, 0));
        jb32.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb32.setEnabled(false);
        jb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb32ActionPerformed(evt);
            }
        });

        jb13.setBackground(new java.awt.Color(0, 0, 0));
        jb13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb13.setEnabled(false);
        jb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb13ActionPerformed(evt);
            }
        });

        jb23.setBackground(new java.awt.Color(0, 0, 0));
        jb23.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb23.setEnabled(false);
        jb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb23ActionPerformed(evt);
            }
        });

        jb33.setBackground(new java.awt.Color(0, 0, 0));
        jb33.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jb33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jb33.setEnabled(false);
        jb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb33ActionPerformed(evt);
            }
        });

        jbInit.setText("INICIAR");
        jbInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb33, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jbInit)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb33, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbInit)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb21ActionPerformed
        // TODO add your handling code here:
        jb21.setEnabled(false);
        simbolo = jogada();
        jb21.setText(simbolo);
        tabuleiro[2][1] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb21ActionPerformed

    private void jb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb31ActionPerformed
        // TODO add your handling code here:
        jb31.setEnabled(false);
        simbolo = jogada();
        jb31.setText(simbolo);
        tabuleiro[3][1] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb31ActionPerformed

    private void jb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb11ActionPerformed
        // TODO add your handling code here:
        jb11.setEnabled(false);
        simbolo = jogada();
        jb11.setText(simbolo);
        tabuleiro[1][1] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb11ActionPerformed

    private void jb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb12ActionPerformed
        // TODO add your handling code here:
        jb12.setEnabled(false);
        simbolo = jogada();
        jb12.setText(simbolo);
        tabuleiro[1][2] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb12ActionPerformed

    private void jb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb22ActionPerformed
        // TODO add your handling code here:
        jb22.setEnabled(false);
        simbolo = jogada();
        jb22.setText(simbolo);
        tabuleiro[2][2] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb22ActionPerformed

    private void jb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb32ActionPerformed
        // TODO add your handling code here:
        jb32.setEnabled(false);
        simbolo = jogada();
        jb32.setText(simbolo);
        tabuleiro[3][2] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb32ActionPerformed

    private void jb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb13ActionPerformed
        // TODO add your handling code here:
        jb13.setEnabled(false);
        simbolo = jogada();
        jb13.setText(simbolo);
        tabuleiro[1][3] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb13ActionPerformed

    private void jb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb23ActionPerformed
        // TODO add your handling code here:
        jb23.setEnabled(false);
        simbolo = jogada();
        jb23.setText(simbolo);
        tabuleiro[2][3] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb23ActionPerformed

    private void jb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb33ActionPerformed
        // TODO add your handling code here:
        jb33.setEnabled(false);
        simbolo = jogada();
        jb33.setText(simbolo);
        tabuleiro[3][3] = simbolo;
        verificarVencedor();
    }//GEN-LAST:event_jb33ActionPerformed

    private void jbInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInitActionPerformed
        // TODO add your handling code here:
        jbInit.setText("REINICIAR");
        reiniciar();
    }//GEN-LAST:event_jbInitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb11;
    private javax.swing.JButton jb12;
    private javax.swing.JButton jb13;
    private javax.swing.JButton jb21;
    private javax.swing.JButton jb22;
    private javax.swing.JButton jb23;
    private javax.swing.JButton jb31;
    private javax.swing.JButton jb32;
    private javax.swing.JButton jb33;
    private javax.swing.JButton jbInit;
    // End of variables declaration//GEN-END:variables
}
